import { prepareDataForValidation } from "formik";

export const columnsNames = [
    { id: 'obra', value: 'Obra' },
    { id: 'descripcion', value: 'Descripción' },
    { id: 'fecha_inicio', value: 'Fecha de inicio' },
    { id: 'fecha_fin', value: 'Fecha de terminación' },
    { id: 'fecha_registro', value: 'Fecha de registro' },
    { id: 'usuario', value: 'Usuario' },//id_usuario
    { id: 'usuario_alta', value: 'Usuario alta registro' },
    { id: 'id_estatus', value: 'Estatus' },
    { id: 'presupuesto', value: 'Presupuesto' },
    { id: 'limite_contratos', value: 'Limite de contratos' },
    { id: 'foto', value: 'Avatar' },
    { id: 'direccion', value: 'Dirección' },
    { id: 'nombre', value: 'Nombre' },
    { id: 'ruta', value: 'Ver documento' },
    { id: 'correo', value: 'Correo electrónico' },
    { id: 'activo', value: 'Activo' },
    { id: 'id_tipo_usuario', value: 'Tipo de usuario' },
    { id: 'id', value: 'ID' },
    { id: 'clave', value: 'Clave' },
    { id: 'proyecto', value: 'Proyecto' },
    { id: 'contrato', value: 'Contrato' },
    { id: 'id_contrato', value: 'ID Contrato' },
    { id: 'fecha_final', value: 'Fecha de terminación' },
    { id: 'importe', value: 'Importe' },
    { id: 'estatus', value: 'Estatus' },
    { id: 'plantilla', value: 'Plantilla' },
    { id: 'terminado', value: 'Terminado' },
    { id: 'nota', value: 'Nota' },
    { id: 'moneda', value: 'Moneda' },
    { id: 'usuarios_asignados', value: 'Usuarios asignados' },
    { id: 'nombre_corto', value: 'Nombre corto' },
    { id: 'rfc', value: 'RFC' },
    { id: 'usuariosAsignadosProyecto', value: 'Administrar usuarios' },
    { id: 'linea_base', value: 'Linea base' },
    { id: 'concepto', value: 'ID Concepto' },
    { id: 'cantidad_contrato', value: 'Cantidad contrato' },
    { id: 'cantidad_visual', value: 'Cantidad visual' },
    { id: 'cantidad_confirmada', value: 'Cantidad confirmada' },
    { id: 'descripcion_estatus', value: 'Estatus' },
    { id: 'volumen_estimar', value: 'Volumen a estimar' },
    { id: 'precio_unitario', value: 'Precio unitario' },
    { id: 'comentarios', value: 'Comentarios' },
    { id: 'cantidad_ejecutada', value: 'Cantidad ejecutada' },
    { id: 'pendiente_estimar', value: 'Pendiente por estimar' },
    { id: 'cantidad_acumulada', value: 'Cantidad acumulada' },
    { id: 'importe_acumulado', value: 'Importe acumulado' },
    { id: 'numero_estimacion', value: '# Estimación' },
    { id: 'fecha_est_definitiva', value: 'Fecha' },
    { id: 'amortizacion', value: 'Amortización' },
    { id: 'subtotal', value: 'Subtotal' },
    { id: 'impuesto_iva', value: 'IVA' },
    { id: 'importe_con_iva', value: 'Importe C/IVA' },
    { id: 'rentenciones', value: 'Retenciones C/IVA' },
    { id: 'saldo_obra_con_iva', value: 'Saldo obra C/IVA' },
    { id: 'avance_obra', value: '% Avance obra' },
    { id: 'factura', value: 'Factura' },
    { id: 'periodo', value: 'Periodo' },
    { id: 'tipo_de_concepto', value: 'Tipo de concepto' },
    { id: 'volumen_estimado', value: 'Volumen estimado' },
    { id: 'volumen_acumulado_anterior', value: 'Volumen acumulado anterior' },
    { id: 'volumen_acumulado_actial', value: 'Volumen acumulado actual' },
    { id: 'precio', value: 'Precio' },
    { id: 'importeAcumuladoAnterior', value: 'Importe acumulado anterior' },
    { id: 'importeAcumuladoActual', value: 'Importe acumulado actual' },
    { id: 'comentarios_estimacion', value: 'Comentarios' },
    { id: 'concepto_', value: 'Concepto' },
    { id: 'cantidad', value: 'Cantidad' },
    { id: 'pu', value: 'PU' },
    { id: 'num_estimacion', value: 'Número estimación' },
    { id: 'numero_estimacion_actual', value: 'Número estimación actual' },
    { id: 'numero_estimacion_anterior', value: 'Número estimación anterior' },
    { id: 'volumen_deducir', value: 'Volumen a deducir' },
    { id: 'volumen_deducido', value: 'Volumen deducido' },
    { id: 'tipo_documento', value: 'Tipo de archivo' },
    { id: 'path', value: 'Ver documento' },
    { id: 'comentario', value: 'Comentario' },
    { id: 'unidad', value: 'Unidad' },
    { id: 'fecha_ejecucion', value: 'Fecha ejecución' },
    { id: 'avance', value: 'Avance' },
    { id: 'avance_acumulado', value: 'Avance acumulado' },
    { id: 'descripcion_concepto', value: 'Descripción concepto' },
    { id: 'descripcion_hito', value: 'Descripción hito' },
    { id: 'cantidad_ejecutar', value: 'Cantidad a ejecutar' },
    { id: 'cantidad_por_ejecutar', value: 'Cantidad por ejecutar' },
    { id: 'suma_visual', value: 'Cantidad visual' },
    { id: 'sum_confirmada', value: 'Cantidad confirmada' },
    { id: 'acumulado', value: 'Acumulado' },
    { id: 'responsable', value: 'Responsables' },
    { id: 'estatus_join', value: "estatus(s)" },
    { id: 'fecha', value: "Fecha" },
    { id: 'frente', value: "Frente" },
    { id: 'id_concepto', value: "ID Concepto" },
    { id: 'inciso', value: "ID Auxiliar" },
    { id: 'num_convenio', value: "# Convenio" },
    { id: 'cantidad_ejecutada_concepto', value: 'Cantidad ejecutada' },
    { id: 'concepto_eee', value: 'Estatus' },
    { id: 'titulo', value: 'Título' },
    { id: 'tipo', value: 'Tipo' },
    { id: 'pronto_pago', value: 'Pronto pago' },
    { id: 'codigo', value: 'Código' },
    { id: 'prioridad', value: 'Prioridad' },
    { id: 'cantidad_proyecto', value: 'Cantidad proyecto' },
    { id: 'total_entradas', value: 'Total entrada' },
    { id: 'total_salidas', value: 'Total salidas' },
    { id: 'disponible', value: 'Disponible' },
    { id: 'insumo', value: 'Insumo' },
    { id: 'fecha_entrada', value: 'Fecha entrada' },
    { id: 'origen', value: 'Origen' },
    { id: 'fecha_salida', value: 'Fecha salida' },
    { id: 'resumen', value: 'Resumen' },
    { id: 'empresa', value: 'Empresa' },
    { id: 'porcentaje_total_proyecto', value: '% Total del proyecto' },
    { id: 'importe_estimado', value: 'Importe estimado' },
    { id: 'porcentaje_estimado_contrato', value: '% Estimado del contrato' },
    { id: 'porcentaje_estimado_proyecto', value: '% Estimado del proyecto' },
    { id: 'por_ejercer', value: 'Por ejercer' },
    { id: 'clasificacion', value: 'Clasificación' },
    { id: 'asignar_usuarios_carpeta_compartida', value: 'Compartir carpeta' },
    { id: 'carpeta', value: 'Carpeta' },
    { id: 'contratista', value: 'Contratista' },
    { id: 'importe_catalogo', value: 'Importe catálogo' },
    { id: 'anticipo_capturado', value: 'Anticipo capturado' },
    { id: 'anticipo', value: 'Anticipo' },
    { id: 'anticipo_contabilizado', value: 'Anticipo contbilizado' },
    { id: 'porcentaje_de_anticipo', value: 'Porcentaje de anticipo' },
    { id: 'amortizacion_de_anticipo', value: 'Amotización de anticipo' },
    { id: 'deductivas', value: 'Deductivas' },
    { id: 'estimado_neto', value: 'Estimado neto' },
    { id: 'estimado_bruto', value: 'Estimado bruto' },
    { id: 'estimado_contabilizado', value: 'Estimado contabilizado' },
    { id: 'estimado_contabilizado', value: 'Estimado contabilizado' },
    { id: 'pendiente_de_contabilizar', value: 'Pendiente de contabilizar' },
    { id: 'pendiente_de_pago', value: 'Pendiente de pago' },
    { id: 'total_contabilizado', value: 'Total contabilizado' },
    { id: 'tipo_contrato', value: 'Tipo de contrato' },
    { id: 'pep', value: 'PEP' },
    { id: 'area', value: 'Área' },
    { id: 'msg_relacion_contratos', value: 'Estatus' },
    { id: 'monto', value: 'Monto' },
    { id: 'monto_pesos', value: 'Monto en pesos' },
    { id: 'estimacion_num', value: '# Estimación' },
    { id: 'fecha_elaboracion', value: 'Fecha de elaboración' },
    { id: 'importe_contratado', value: 'Importe contratado' },
    { id: 'importe_estimacion', value: 'Importe estimación' },
    { id: 'sub_tota_importes_por_estimacion', value: 'Subtotal de importes por estimación' },
    { id: 'fondo_garantia', value: 'Fondo de garantia' },
    { id: 'notas', value: 'Notas' },

    { id: '0Diciembre 2022', value: 'Diciembre 2022' },
    { id: '0Diciembre 2023', value: 'Diciembre 2023' },
    { id: '0Diciembre 2024', value: 'Diciembre 2024' },
    { id: '0Diciembre 2025', value: 'Diciembre 2025' },
    { id: '0Diciembre 2026', value: 'Diciembre 2026' },
    { id: '0Diciembre 2027', value: 'Diciembre 2027' },

    { id: '0Enero 2024', value: 'Enero 2024' },
    { id: '1Febrero 2024', value: 'Febrero 2024' },
    { id: '2Marzo 2024', value: 'Marzo 2024' },
    { id: '3Abril 2024', value: 'Abril 2024' },
    { id: '4Mayo 2024', value: 'Mayo 2024' },
    { id: '5Junio 2024', value: 'Junio 2024' },
    { id: '6Julio 2024', value: 'Julio 2024' },
    { id: '7Agosto 2024', value: 'Agosto 2024' },
    { id: '8Septiembre 2024', value: 'Septiembre 2024' },
    { id: '9Octubre 2024', value: 'Octubre 2024' },
    { id: '10Noviembre 2024', value: 'Noviembre 2024' },
    { id: '0Noviembre 2024', value: 'Noviembre 2024' },
    { id: '11Diciembre 2024', value: 'Diciembre 2024' },

    { id: '0Enero 2023', value: 'Enero 2023' },
    { id: '1Febrero 2023', value: 'Febrero 2023' },
    { id: '2Marzo 2023', value: 'Marzo 2023' },
    { id: '3Abril 2023', value: 'Abril 2023' },
    { id: '4Mayo 2023', value: 'Mayo 2023' },
    { id: '5Junio 2023', value: 'Junio 2023' },
    { id: '6Julio 2023', value: 'Julio 2023' },
    { id: '7Agosto 2023', value: 'Agosto 2023' },
    { id: '8Septiembre 2023', value: 'Septiembre 2023' },
    { id: '9Octubre 2023', value: 'Octubre 2023' },
    { id: '10Noviembre 2023', value: 'Noviembre 2023' },
    { id: '11Diciembre 2023', value: 'Diciembre 2023' },

    { id: '0Enero 2022', value: 'Enero 2022' },
    { id: '1Febrero 2022', value: 'Febrero 2022' },
    { id: '2Marzo 2022', value: 'Marzo 2022' },
    { id: '3Abril 2022', value: 'Abril 2022' },
    { id: '4Mayo 2022', value: 'Mayo 2022' },
    { id: '5Junio 2022', value: 'Junio 2022' },
    { id: '6Julio 2022', value: 'Julio 2022' },
    { id: '7Agosto 2022', value: 'Agosto 2022' },
    { id: '8Septiembre 2022', value: 'Septiembre 2022' },
    { id: '9Octubre 2022', value: 'Octubre 2022' },
    { id: '10Noviembre 2022', value: 'Noviembre 2022' },
    { id: '11Diciembre 2022', value: 'Diciembre 2022' },

    { id: '0Enero 2021', value: 'Enero 2021' },
    { id: '1Febrero 2021', value: 'Febrero 2021' },
    { id: '2Marzo 2021', value: 'Marzo 2021' },
    { id: '3Abril 2021', value: 'Abril 2021' },
    { id: '4Mayo 2021', value: 'Mayo 2021' },
    { id: '5Junio 2021', value: 'Junio 2021' },
    { id: '6Julio 2021', value: 'Julio 2021' },
    { id: '7Agosto 2021', value: 'Agosto 2021' },
    { id: '8Septiembre 2021', value: 'Septiembre 2021' },
    { id: '9Octubre 2021', value: 'Octubre 2021' },
    { id: '10Noviembre 2021', value: 'Noviembre 2021' },
    { id: '11Diciembre 2021', value: 'Diciembre 2021' },

    { id: '0Enero 2020', value: 'Enero 2020' },
    { id: '1Febrero 2020', value: 'Febrero 2020' },
    { id: '2Marzo 2020', value: 'Marzo 2020' },
    { id: '3Abril 2020', value: 'Abril 2020' },
    { id: '4Mayo 2020', value: 'Mayo 2020' },
    { id: '5Junio 2020', value: 'Junio 2020' },
    { id: '6Julio 2020', value: 'Julio 2020' },
    { id: '7Agosto 2020', value: 'Agosto 2020' },
    { id: '8Septiembre 2020', value: 'Septiembre 2020' },
    { id: '9Octubre 2020', value: 'Octubre 2020' },
    { id: '10Noviembre 2020', value: 'Noviembre 2020' },
    { id: '11Diciembre 2020', value: 'Diciembre 2020' },

    { id: '0Enero 2025', value: 'Enero 2025' },
    { id: '1Febrero 2025', value: 'Febrero 2025' },
    { id: '2Marzo 2025', value: 'Marzo 2025' },
    { id: '3Abril 2025', value: 'Abril 2025' },
    { id: '4Mayo 2025', value: 'Mayo 2025' },
    { id: '5Junio 2025', value: 'Junio 2025' },
    { id: '6Julio 2025', value: 'Julio 2025' },
    { id: '7Agosto 2025', value: 'Agosto 2025' },
    { id: '8Septiembre 2025', value: 'Septiembre 2025' },
    { id: '9Octubre 2025', value: 'Octubre 2025' },
    { id: '10Noviembre 2025', value: 'Noviembre 2025' },
    { id: '11Diciembre 2025', value: 'Diciembre 2025' },

    { id: '0Enero 2026', value: 'Enero 2026' },
    { id: '1Febrero 2026', value: 'Febrero 2026' },
    { id: '2Marzo 2026', value: 'Marzo 2026' },
    { id: '3Abril 2026', value: 'Abril 2026' },
    { id: '4Mayo 2026', value: 'Mayo 2026' },
    { id: '5Junio 2026', value: 'Junio 2026' },
    { id: '6Julio 2026', value: 'Julio 2026' },
    { id: '7Agosto 2026', value: 'Agosto 2026' },
    { id: '8Septiembre 2026', value: 'Septiembre 2026' },
    { id: '9Octubre 2026', value: 'Octubre 2026' },
    { id: '10Noviembre 2026', value: 'Noviembre 2026' },
    { id: '11Diciembre 2026', value: 'Diciembre 2026' },

    { id: 'clasificacion_pmo', value: 'Clasificación PMO' },
    { id: 'acomulado_anios_anteriores', value: 'Acomulado años anteriores' },
    { id: 'total_anio', value: 'Acomulado del año' },

    { id: 'avance_fisico', value: 'Avance fisico' },
    { id: 'avance_financiero', value: 'Avance financiero' },
    { id: 'avance_programado', value: 'Avance programado' },
    { id: 'tiempo_trascurrido_vegencia_contrato', value: 'Tiempo trasnscurrido de la vigencia del contrato' },
    { id: 'porcentaje_avance_fisico', value: 'Porcentaje avance fisico' },
    { id: 'porcentaje_avance_financiero', value: 'Porcentaje avance financiero' },
    { id: 'porcentaje_avance_financiero_programado', value: 'Porcentaje avance financiero programado' },

    { id: 'importe_obra_ejecutada_no_estimada', value: 'Importe de obra ejecutada no estimada' },
    { id: 'por_amortizar', value: 'Por amortizar' },
    { id: 'observaciones', value: 'Observaciones' },
    { id: 'sub_total_importes_por_estimacion', value: 'Subtotal de importes por estimación' },
    { id: 'cta_contratos', value: '# contratos en esta clasificación' },
    { id: 'porcentaje_proyecto', value: '% del proyecto' },
    { id: 'estimado_clasificacion', value: 'Estimado' },
    { id: 'procentaje_estimacion_proyecto', value: '% estimacion' },
    { id: 'sss', value: 'Estatus' },
    { id: 'perfil', value: 'Perfil' },
    { id: 'usuarios_cta', value: '# Usuarios' },
    { id: 'id_transaccion', value: 'ID de transacción' },
    { id: 'FechaActualizacion', value: 'Fecha y hora de la actualización' },
    { id: 'hrs', value: 'HRS.' },
    { id: 'iva', value: 'IVA' },
    { id: 'retenciones', value: 'Retenciones' },
    { id: 'presupuesto_parametrico', value: 'Presupuesto paramétrico' },
    { id: 'contratado', value: 'Contratado' },
    { id: 'cotizado', value: 'Cotizado' },
    { id: 'amortizado', value: 'Amortizado' },
    { id: 'estimado', value: 'Estimado' },
    { id: 'diferencia', value: 'Diferencia' },
    { id: 'a_ejercer', value: 'A ejercer'},
    { id: 'dias_trascurridos_parcial', value: 'Dias trascurridos parcial'},
    { id: 'dias_trascurridos_acumulado', value: 'Dias trascurridos acumulado'},
    { id: 'deducciones', value: 'Deducciones'},
    { id: 'ahorro', value: 'Ahorro'},
    { id: 'fondo_grantia', value: 'Fondo de garantia'},
    { id: 'deductiva', value: 'Deductiva'},
    { id: 'pendiente_contabilizar', value: 'Pendiente de contabilizar'},
    { id: 'responsables', value: 'Responsables'},
    { id: 'one', value: 'OENE'},
    { id: 'oene', value: 'OENE'},
    { id: 'conceptos', value: 'Concepto'},
    { id: 'avances', value: 'Avances'},
    { id: 'importe_contrato', value: 'Importe contratado'},
    {id: 'similitud_busqueda', value: 'Porcentaje de similitud con tus parametros de busqueda'},
    {id: 'estatusAvance', value: 'Estatus'},
    {id: 'fecha_alta_avanece', value: 'Fecha alta avance'},
    {id: 'fecha_confirmacion_avance', value: 'Fecha confirmación avance'},
    {id: 'nombre_usuario ', value: 'Usuario'},
    {id:'id_obra', value: 'Obra ID'},
    {id:'mes_registro', value: 'Mes de registro'},
    {id:'ano_registro', value: 'Año de registro'},
    {id:'ubicacion', value: 'Ubicación'},
    {id:'saldo_obra_ejecutada', value: 'Saldo obra ejecutada'},
    {id:'creador', value: 'Creador'},
    {id:'total', value: 'Total'},
    {id:'retencion', value: 'Retención'},
];
