const textosMx = {
   'general_puesto': 'Puesto',
   'general_correo': 'Correo electrónico',
   'general_continuar':'Continuar',
   'general_nombre': 'Nombre',
   'general_perfil': 'Perfil',
   'general_acumulado_anterior': 'Acumulado anterior',
   'general_periodo': 'Periodo',
   'general_retencion': 'Retención',
   'input_iva_cargos_adicionales': 'Iva cargos adicionales',
   'regresar_inicio': 'Regresar al inicio',
   'general_alta': 'Alta',
   'general_guardar': 'Guardar',
   'general_reprogramar':'Reprogramar',
   'menu_cerrar_hito':'Cerrar hito',
   'general_guardar_estimacion_definitiva': 'Guardar estimación definitiva',
   'general_actualizar': 'Actualizar',
   'general_enviar': 'Enviar',
   'general_confirmar': 'Confirmar',
   'general_agregar': 'Agregar',
   'general_asignar': 'Asignar',
   'general_usuario': 'Usuario',
   'general_sin_resultados': 'Sin resultados',
   'general_sin_resultados_avances_confirmar': 'No hay avances por confirmar en este momento, serás direccionado a la lista de frentes',
   'general_cancelar': 'Cancelar',
   'general_editar': 'Editar',
   'general_eliminar': 'Eliminar',
   'general_reactivar': 'Reactivar',
   'general_subir_foto': 'Subir foto',
   'general_nota': 'Nota',
   'general_ver_notas': 'Ver notas',
   'general_subir_nota': 'Subir nota',
   'general_ver_fotos': 'Ver fotos',
   'general_programa': 'Programa',
   'general_buscar': 'Buscar',
   'general_realizar_estimacion': 'Realizar estimación',
   'general_ver_frente': 'Ver frente',
   'general_esta_estimacion': 'Esta estimación',
   'general_acumulado_actual': 'Acumulado actual',
   'general_saldo': 'Saldo',
   'general_saldo_amortizar': 'Saldo por amortizar',
   'general_deduccion_estimacion': 'Deducción esta estimación',
   'http_error_general_operacion': 'Error al realizar la operación',
   'http_exito_general_operacion': 'Éxito al realizar la operación',
   'http_exito_registrar': 'Éxito al registrar',
   'http_error_registrar': 'Error al registrar',
   'input_tipo':'Tipo',
   'http_exito_actualizar': 'Éxito al actualizar',
   'http_error_actualizar': 'Error al actualizar',
   'http_exito_confirmar': 'Éxito al confirmar',
   'http_error_confirmar': 'Error al confirmar',
   'http_exito_eliminar': 'Éxito al eliminar',
   'http_error_eliminar': 'Error al eliminar',
   'dashboard_charts_pregunta_eliminar': '¿Desea eliminar la gráfica  del dashboard?',
   'gestion_contratos_pregunta_actualizar_estatus': '¿Desea actualizar el estatus de este contrato?',
   'add_catalogo_form_hook_actualizar_pregnta': '¿Estás seguro de actualizar los datos de este catálogo?',
   'add_catalogo_form_hook_reactivar_pregnta': '¿Estás seguro de reactivar este elemento del catálogo?',
   'add_catalogo_form_hook_eliminar_pregnta': '¿Estás seguro de eliminar este elemento del catálogo?',
   'add_proyectos_usuario_btn_agregar_nuevo': 'Agregar nuevo usuario',
   'add_proyectos_usuario_btn_terminar_proceso': 'Terminar proceso',
   'add_proyectos_usuario_pregunta_asignar_contrato': '¿Desea agregar contratos a este proyecto?',
   'add_proyectos_usuario_pregunta_asignar_contrato_desde_formulario': '¿Desea agregar contratos al proyecto seleccionado en el paso anterior?',
   'gestion_contratos_alertas': 'Alertas',
   'gestion_contratos_anticipo': 'Anticipo',
   'gestion_contratos_categoria': 'Categoría',
   'gestion_contratos_contrato_liberado': 'Contrato liberado',
   'gestion_contratos_estatus_firma': 'Estatus firma',
   'gestion_contratos_tipo_proyecto': 'Tipo proyecto',
   'gestion_contratos_fecha_limite': 'Fecha limite',
   'gestion_contratos_fecha_registro': 'Fecha registro',
   'gestion_contratos_propietario': 'Propietario',
   'gestion_contratos_reclasificacion': 'Reclasificación',
   'gestion_contratos_tipo_cambio': 'Tipo de cambio',
   'gestion_contratos_tolerancia': 'Tolerancia',
   'gestion_contratos_autorizado': 'Autorizado',
   'gestion_contratos_titulo_parametros_contrato': 'Parametros del contrato',
   'gestion_contratos_titulo_clasificacion_contrato': 'Clasificación del contrato',
   'gestion_contratos_id_clasificacion_contrato': 'Id clasificación del contrato',
   'gestion_contratos_clave_clasificacion_contrato': 'Clave clasificación del contrato',
   'gestion_contratos_nombre_clasificacon_contrato': 'Nombre clasificación del contrato',
   'gestion_contratos_titulo_contratista': 'Contratista',
   'gestion_contratos_id_contratista': 'Id contratista',
   'gestion_contratos_contratista': 'Contratista',
   'gestion_contratos_contratista_correo': 'Correo electrónico',
   'gestion_contratos_titulo_pep': 'Cuenta contable',
   'gestion_contratos_pep_id': 'Id Cuenta contable',
   'gestion_contratos_pep_nombre': 'Nombre de la cuenta contable',
   'gestion_contratos_pep_descripcion': 'Descripción',
   'gestion_contratos_cliente_titulo': 'Cliente',
   'gestion_contratos_cliente_id': 'Id del cliente',
   'gestion_contratos_cliente_nombre': 'Nombre del cliente',
   'gestion_contratos_cliente_rfc': 'RFC del cliente',
   'gestion_contratos_responsable_titulo': 'Responsable',
   'gestion_contratos_responsable_id': 'Id del responsable',
   'gestion_contratos_responsable_nombre': 'Nombre del responsable',
   'gestion_contratos_responsable_correo': 'Correo electrónico del responsable',
   'gestion_contratos_tipo_contrato_titulo': 'Tipo de contrato',
   'gestion_contratos_tipo_contrato_id': 'Id tipo de contrato',
   'gestion_contratos_tipo_contrato_clave': 'Clave del tipo de contrato',
   'gestion_contratos_tipos_contrato_nombre': 'Nombre del tipo de contrato',
   'gestion_contratos_tipo_contrato_ext_titulo': 'Tipo de contrato ext.',
   'gestion_contratos_tipo_contrato_ext_id': 'Id tipo de contrato ext.',
   'gestion_contratos_tipo_contrato_ext_clave': 'Clave del tipo de contrato ext.',
   'gestion_contratos_tipos_contrato_ext_nombre': 'Nombre del tipo de contrato ext.',
   'gestion_contratos_especialidad_titulo': 'Especialidad',
   'gestion_contratos_especialidad_id': 'Id Especialidad',
   'gestion_contratos_especialidad_clave': 'Clave de la Especialidad',
   'gestion_contratos_especialidad_nombre': 'Nombre de la Especialidad',
   'gestion_contratos_proyecto_titulo': 'Proyecto',
   'gestion_contratos_proyecto_id': 'Id proyecto',
   'gestion_contratos_proyecto_nombre': 'Nombre del proyecto',
   'gestion_contratos_proyecto_descripcion': 'Descripción del proyecto',
   'gestion_contratos_autorizador_titulo': 'Autorizador',
   'gestion_contratos_autorizador_id': 'Id autorizador',
   'gestion_contratos_autorizador_nombre': 'Nombre del autorizador',
   'gestion_contratos_autorizador_correo': 'Correo electrónico del autorizador',
   'gestion_contratos_exito_eliminar_asignacion': 'Éxito al eliminar la asignación de usuario',
   'gestion_contratos_error_eliminar_asignacion': 'Error al eliminar la asignación de usuario',
   'gestion_contratos_pregunta_eliminar_asignacion_usuario_contrato': '¿Desea eliminar la asignación de este usuario para este contrato?',
   'gestion_contratos_btn_eliminar_asignacion_usuario': 'Desasignar usuario',
   'gestion_contratos_info_sin_usuarios_asignados': 'Sin usuarios asignados',
   'http_exito_actualizar_estatus': 'Éxito al desactivar el registro',
   'http_error_actualizar_estatus': 'Error al desactivar el registro',
   'catalogos_error_obtener': 'Error al obtener el catálogo',
   'get_elementos_error': 'Error al obtener los registros',
   'menu_home_advertencia_navegar': 'Para poder navegar en el sitio, antes debe seleccionar un espacio de trabajo',
   'http_exito_registrar_cliente': 'Éxito al guardar el cliente',
   'http_error_registrar_cliente': 'Error al registrar el cliente',
   'http_exito_registrar_asignaciones': 'Éxito al registrar las asignaciones',
   'http_error_registrar_asignaciones': 'Error al registrar las asignaciones',
   'http_exito_registrar_asignacion': 'Éxito al hacer la asignación',
   'http_error_asignacion_usuario': 'Ocurrió un error al asignar al usuario',
   'stepper_contratos_paso_0': 'Selecciona proyecto',
   'stepper_contratos_paso_1': 'Formulario contrato',
   'stepper_contratos_paso_2': 'Vista previa contrato',
   'stepper_contratos_paso_2.1': 'Parametros del contrato',
   'stepper_contratos_paso_3': '¿Asignar usuarios al contrato?',
   'stepper_contratos_paso_4': 'Asignación de usuarios',
   'add_contratos_pregunta': '¿Desea agregar usuarios al contrato?',
   'add_contratos_pregunta_respuesta_1': 'Agregar usuarios',
   'add_contratos_pregunta_respuesta_2': 'No, hacerlo después',
   'add_contrato_tarjeta_contrato_vista_previa_info': 'Esta es una vista previa del contrato y así es como se guardara el registro',
   'login_error': 'Error al iniciar sesión',
   'recuperacion_contrasena_inicio_proceso_exito': 'Se ha iniciado el proceso para la recuperación de la contraseña, por favor revise su correo electrónico para continuar con el proceso',
   'recuperacion_contrasena_inicio_proceso_error': 'Error al iniciar proceso para la recuperación de la contraseña',
   'recuperacion_contrasena_exito_al_actualizar': 'Éxito al actualizar la contraseña',
   'recuperacion_contrasena_error_al_actualizar': 'Error al actualizar la contraseña',
   'permiso_usuario_exito_asignacion': 'Éxito al asignar el permiso',
   'permiso_usuario_exito_elimina_asignacion': 'Éxito al eliminar permiso',
   'repositorio_pregunta_eliminar_documento': '¿Desea eliminar el documento seleccionado?',
   'repositorio_exito_elimina_documento': 'Éxito al dar de baja el documento',
   'repositorio_error_elimina_documento': 'Error al dar de baja el documento',
   'repositorio_exito_alta_documento': 'Éxito al dar de alta el documento',
   'repositorio_error_alta_documento': 'Error al dar de alta el documento',
   'repositorio_obten_documentos': 'Error al obtener los documentos',
   'contratos_page_no_contratos_asignados': 'Ningún contrato le ha sido asignado, contacte con su coordinador para que le asignen uno',
   'alta_contratos_page_proceso_completo_sin_usuarios': '¡Ha finalizado el registro del contrato!',
   'alta_contratos_page_proceso_completo_con_usuarios': '¡Ha finalizado el registro del contrato y la asignación de usuarios!',
   'add_contratos_card_usuario_contrato_nuevo_usuario': 'Nuevo usuario',
   'add_contratos_card_usuario_contrato_usuario_existente': 'Usuario existente',
   'add_contratos_card_usuario_contrato_guardar_seleccion': 'Guardar seleccionados',
   'add_contratos_card_usuario_contrato_terminar_proceso': 'Terminar asignación de usuarios',
   'card_usuarios_contrato_existe_orden': 'Ese orden ya fue seleccionado, por favor selecciona un orden que no esté seleccionado',
   'dashboard_page_error_obtener': 'Ocurrió un error al recuperar el dashboard, intente de nuevo',
   'login_page_titulo': 'Inicio de sesión',
   'login_page_ingrese_credenciales': 'Ingrese usuario y contraseña',
   'login_page_texto_recuperar_contrasena_1': 'Ingresa al siguiente',
   'login_page_texto_recuperar_contrasena_2': 'enlace',
   'login_page_texto_recuperar_contrasena_3': 'para recuperar tu contraseña',
   'main_page_se_establecio_espacio_1': 'Se ha establecido el proyecto',
   'main_page_se_establecio_espacio_2': 'como espacio de trabajo',
   'main_page_establece_espacio_de_trabajo_instruccion': 'Establece tu espacio de trabajo seleccionando el proyecto deseado',
   'main_page_titulo': 'Proyectos vigentes',
   'main_page_titulo_2': 'Proyectos concluidos',
   'main_page_titulo_3':'Tablero de proyectos global',
   'main_page_pregunta_asignar_usuarios': '¿Desea asignar usuarios a este proyecto?',
   '404_page_titulo': 'Página no encontrada',
   'password_recover_page_titulo': 'Recuperación de contraseña',
   'password_recover_validacion_page_titulo': 'Actualización de la contraseña',
   'password_recover_validacion_page_token_invalido': 'El token proporcionado es inválido',
   'add_charts_component_info_1': 'Si el elemento que quiere dar de alta es de tipo indicador, el campo Query debe de contener la siguiente estructura',
   'add_charts_component_info_2': '1 El resultado debe ser un arreglo de objetos',
   'add_charts_component_info_3': '2 El resultado debe contener un solo elemento',
   'add_charts_component_info_4': '3 el objeto debe tener la propiedad total',
   'add_charts_component_info_5': 'Ejemplo',
   'add_charts_component_recomienda': 'En el campo Query sql, se recomienda que sea una vista y el resultado debe de tener al menos una columna con el nombre labels',
   'add_charts_hook_tipos_graficas_barras': 'Barras',
   'add_charts_hook_tipos_graficas_lineas': 'Líneas',
   'add_charts_hook_tipos_graficas_pay': 'Pastel',
   'add_charts_hook_tipos_graficas_dona': 'Dona',
   'add_charts_hook_tipos_graficas_polar': 'Polar',
   'add_charts_hook_tipos_graficas_radar': 'Radar',
   'add_charts_hook_tipos_graficas_tabla': 'Tabla',
   'add_charts_hook_tipos_graficas_dato_unico': 'Indicador dato único',
   'add_charts_hook_tamano_grafica_1': 'Toda la pantalla',
   'add_charts_hook_tamano_grafica_2': 'Mitad de la pantalla',
   'add_charts_hook_tamano_grafica_3': '1 cuarta parta del espacio de la pantalla',
   'add_charts_hook_tamano_grafica_4': '3 tercer parta del espacio de la pantalla',
   'add_charts_hook_tamano_grafica_5': '1 sexta parta del espacio de la pantalla',
   'catalogo_formulario_principal_acordion_1': 'Agregar un nuevo elemento al catálogo',
   'catalogo_formulario_principal_acordion_2': 'Editar / eliminar un elemento al catálogo',
   'btn_firmar_documento': 'Firmar documento',
   'input_firma': 'Firma',
   'input_firma_descripcion': 'Ingresa tu clave',
   'input_cerrado': 'Cerrado',
   'input_plaza': 'Plaza',
   'input_tarea': 'Tarea',
   'input_homologado': 'Homologado',
   'input_tipo_concepto': 'Tipo de concepto',
   'input_nombre': 'Nombre',
   'input_nombre_descripcion': 'Ingrese el nombre',
   'input_nombre_corto': 'Nombre corto',
   'input_nombre_corto_descripcion': 'Ingrese el nombre corto',
   'input_rfc': 'RFC',
   'input_rfc_descripcion': 'Ingrese el RFC',
   'input_titulo': 'Titulo',
   'input_titulo_descripcion': 'Ingrese el titulo',
   'input_query': 'Query',
   'input_query_descripcion': 'Escriba el query SQL',
   'input_tipo_grafica': 'Tipo de grafica',
   'input_es_vertical_pregunta': '¿Es grafica con orientación Vertical?',
   'input_es_apilada_pregunta': '¿Es grafica con elementos apilados?',
   'input_rellena_espacios_pregunta': '¿Rellena los espacios en graficas lineales?',
   'input_tamano_grafica': 'Tamaño de la grafica',
   'input_contrato': 'Contrato',
   'input_tipo_nota': 'Tipo de nota',
   'input_contrato_descripcion': 'Ingrese el contrato',
   'input_id_contrato': 'Id del contrato',
   'input_id_contrato_descripcion': 'Ingrese el id del contrato',
   'input_contratista': 'Contratista',
   'input_contratista_descripcion': 'Ingrese el contratista',
   'input_importe_contrado': 'Importe contratado',
   'input_importe_pagar': 'Importe a pagar',
   'input_importe': 'Importe',
   'input_importe_descripcion': 'Ingrese el importe',
   'input_fecha_inicio': 'Fecha de inicio',
   'input_fecha_final': 'Fecha de término',
   'fecha_de_entrega': 'Fecha de terminación',
   'input_fecha_registro': 'Fecha de registro',
   'input_fecha_pedido': 'Fecha de pedido',
   'input_estatus': 'Estatus',
   'input_estatus_parametro': 'Estatus parametro',
   'input_estatus_bloqueo': 'Estatus bloqueo',
   'input_cliente': 'Cliente',
   'input_extranjero': 'Extranjero',
   'input_responsable': 'Responsable',
   'input_autorizado': 'Autorizado',
   'input_autorizador': 'Autorizador',
   'input_plantilla': 'Plantilla',
   'input_plantilla_descripcion': 'Ingrese la plantilla',
   'input_terminado': 'Terminado',
   'input_nota': 'Notas',
   'input_nota_descripcion': 'Ingrese sus notas',
   'inpput_tipo_contrato': 'Tipo de contrato',
   'inpput_tipo_contrato_descripcion': 'Ingrese el tipo de contrato',
   'input_obra_principal': 'Obra principal',
   'input_tipo_de_proyecto': 'Tipo de proyecto',
   'input_pep': 'Cuenta contable',
   'input_pep_descripcion': 'Ingrese el nombre de la cuenta contable',
   'input_moneda': 'Moneda',
   'input_anticipo': 'Anticipo',
   'input_anticipo_descripcion': 'Ingrese el anticipo',
   'input_categoria': 'Categoría',
   'input_categoria_descripcion': 'Ingrese la Categoría',
   'input_alertas': 'Alertas',
   'input_fecha_limite': 'Fecha limite',
   'input_reclasificacion': 'Reclasificación',
   'input_clasificacion_frente': 'Clasificación del frente',
   'input_propietario': 'Propietario',
   'input_tipo_contrato_externo': 'Tipo de contrato externo',
   'input_tolerancia': 'Tolerancia',
   'input_tolerancia_descripcion': 'Ingrese la tolerancia',
   'input_estatus_firma': 'Estatus firma',
   'input_estatus_firma_descripcion': 'Ingrese el estatus firma',
   'input_contrato_liberado': 'Contrato liberado',
   'input_contrato_liberado_descripcion': 'Ingrese el contrato liberado',
   'input_clasificacion_contrato': 'Clasificación del contrato',
   'input_tipo_de_cambio': 'Tipo de cambio',
   'input_tipo_de_cambio_descripcion': 'Ingrese el tipo de cambio',
   'input_especialidad': 'Especialidad',
   'input_sub_especialidad': 'Subespecialidad',
   'input_perfil': 'Perfil',
   'input_frecuencia_frecuencia': 'Ingrese la frecuencia',
   'input_frecuencia': 'Frecuencia',
   'input_pagina_inicio': 'Página de inicio',
   'input_orden': 'Orden',
   'input_orden_descripcion': 'Ingrese el orden',
   'input_usaurio_descripcion': 'Ingrese el usuario',
   'input_correo_descripcion': 'Ingrese el correo electrónico',
   'input_telefono': 'Teléfono',
   'input_telefono_descripcion': 'Ingrese el teléfono',
   'input_tipo_usuario': 'Tipo de usuario',
   'input_contrasena': 'Contraseña',
   'input_contrasena_descripcion': 'Ingrese la contraseña',
   'input_contrasena_confirmacion': 'Confirme la contraseña',
   'input_contrasena_confirmacion_descripcion': 'Ingrese la contraseña',
   'input_descripcion': 'Descripción',
   'input_descripcion_descripcion': 'Ingrese la descripción',
   'input_id_externo': 'Id externo',
   'input_id_externo_descripcion': 'Ingrese el id externo',
   'input_proyecto': 'Proyecto',
   'input_proyecto_descripcion': 'Ingrese el nombre del proyecto',
   'input_unidad': 'Unidad',
   'input_unidad_descripcion': 'Ingrese la unidad',
   'input_precio': 'Precio',
   'input_precio_descripcion': 'Ingrese el precio',
   'input_id_tipo': 'Id tipo',
   'input_clave': 'Clave',
   'input_clave_descripcion': 'Ingrese la clave',
   'input_latitud': 'Latitud',
   'input_latitud_descripcion': 'Ingrese la latitud',
   'input_folio': 'Folio',
   'input_folio_descripcion': 'Ingrese el folio',
   'input_monto': 'Monto',
   'input_monto_descripcion': 'Ingrese el Monto',
   'input_longitud': 'Longitud',
   'input_longitud_descripcion': 'Ingrese la longitud',
   'input_limite_contratos': 'Límite de contratos',
   'input_limite_contratos_descripcion': 'Ingrese el límite de contratos',
   'input_foto': 'Avatar',
   'input_cotizacion': 'Cotización',
   'input_cotizacion_descripcion': 'Ingrese la cotización',
   'input_presupuesto': 'Presupuesto',
   'input_presupuesto_descripcion': 'Ingrese el presupuesto',
   'input_cuenta': 'Cuenta',
   'input_cuenta_descripcion': 'Ingrese la cuenta',
   'input_imputable': 'Imputable',
   'input_tipo_catalogo': 'Tipo de catálogo',
   'input_usuario': 'Usuario',
   'input_usuario_descripcion': 'Ingrese el usuario',
   'input_fecha': 'Fecha',
   'input_inciso': 'ID auxiliar',
   'input_inciso_descripcion': 'Ingrese el ID auxiliar',
   'input_clavePresupuestariaCompleta': 'Clave presupuestaría completa',
   'input_clavePresupuestariaCompleta_descripcion': 'Ingrese la clave presupuestaría completa',
   'input_asignacionIva': "Asignación C/IVA",
   'input_asignacionIva_descripcion': "Ingrese la asignación C/IVA",
   'input_origenRecursos': "Origen de los recursos",
   'input_origenRecursos_descripcion': "Ingrese el origen de los recursos",
   'input_datosRecursos': "Datos de los recursos",
   'input_datosRecursos_descripcion': "Ingrese los datos de los recursos",
   'input_modalidadLiquidacion': 'Modalidad de la adjudicación',
   'input_modalidadLiquidacion_descripcion': 'Ingrese la modalidad de la adjudicación',
   'input_fechaContratoNumOperacion': 'Fecha contrato num(s) operación',
   'input_contrato_numero': 'Contrato número ',
   'input_contrato_numero_descripcion': 'Ingrese el contrato número',
   'input_contrato_tipo': 'Tipo de contrato ',
   'input_contrato_tipo_descripcion': 'Ingrese el tipo de contrato',
   'input_ubicacion': 'Ubicación',
   'input_ubicacion_descripcion': 'Ingrese la ubicación',
   'input_fechaEstimacionDefinitiva': 'Fecha de estimación definitiva',
   'input_numeroEstimacionDefinitiva': 'Número de estimación definitiva',
   'input_numeroEstimacionDefinitivainfo': 'Estimación definitiva número',
   'input_numeroEstimacionDefinitiva_descripcion': 'Ingrese el número de estimación definitiva',
   'input_fecha_ejecucion': 'Fecha de ejecución [Formato (dd-mm-aaaa)]',
   'input_fecha_ejecucion_descripcion': 'Ingrese la fecha de ejecución',
   'input_deducciones': 'Deducciones',
   'input_otrosCargos': 'Otros cargos',
   'input_estimacion': 'Seleccione la estimación',
   'input_cargos_adicionales': 'Cargos adicionales',
   'input_saldo_pagar_esta_estimacion': 'Saldo a pagar de esta estimación',
   'input_otrosCargosDescripcion': 'Descripción otros cargos',
   'input_inspeccionObras': 'Inspección de obras',
   'input_impuestoSRenta': 'Impuesto S/Renta',
   'input_fondeGarantia': 'Fondo de garantía %',
   'input_fondeGarantia_sin_porcentaje': 'Fondo de garantía',
   'input_anticipo_porcentaje': 'Anticipo %',
   'input_estimado': 'Estimado',
   'input_deductivas': 'Deductivas',
   'amortizacion': 'Amortización',
   'input_amortizacion': '% Amortización',
   'input_devolucionRetencion': 'Devolución por retención',
   'input_deduccionesOtrosCargos': 'Retención y otros cargos',
   'input_empresa': 'Empresa',
   'input_empresa_descripcion': 'Ingrese el nombre de la empresa a la que pertenece',
   'input_subTotal': 'Subtotal',
   'input_iva': 'Imp 16% IVA',
   'input_iva_retencion': 'IVA retención',
   'input_imp_total': 'Imp total',
   'input_retencionesImpuestos': 'Retenciones/impuestos',
   'input_retencion': 'Retención',
   'input_saldoPagarObraEjecutada': 'Saldo a pagar de la obra ejecutada',
   'input_alcanceLiquido': 'Alcance liquido',
   'input_frente': 'Frente',
   'input_frente_descripcion': 'Ingrese el nombre del frente',
   'input_area_expide': 'Área que expide',
   'input_area_expide_descripcion': 'Ingrese el área que expide',
   'input_fecha_contrato': 'Fecha de contrato',
   'input_modalidad': 'Modalidad',
   'input_modalidad_descripcion': 'Ingrese la modalidad',
   'input_clave_presupuestaria': 'Clave presupuestaria',
   'input_clave_presupuestaria_descripcion': 'Ingrese la clave presupuestaria',
   'input_oficina_pagadora': 'Oficina pagadora',
   'input_oficina_pagadora_descripcion': 'Ingrese la oficina pagadora',
   'input_numero': 'Número',
   'input_numero_descripcion': 'Ingrese el número',
   'input_numero_pedido': 'Número de pedido',
   'input_numero_pedido_descripcion': 'Ingrese el número de pedido',
   'input_amoritzacion': 'Amortización',
   'input_amoritzacion_descripcion': 'Ingrese la amortización',
   'input_asignacion_iva': 'Asignación IVA',
   'input_asignacion_iva_descripcion': 'Ingrese la asignación IVA',
   'input_fecha_pago_lvpl': 'Fecha pago',
   'input_pagado': 'Pagado',
   'input_pagado_descripcion': 'Ingrese el valor',
   'input_tipo_cambio': 'Tipo de cambio',
   'input_tipo_cambio_descripcion': 'Ingrese el tipo de cambio',
   'general_mensaje_navega_sin_espacio': 'Aun no ha establecido su espacio de trabajo, por favor seleccione un proyecto para establecer un espacio de trabajo',
   'general_mensaje_navega_sin_contrato': 'Aun no ha seleccionado un contrato, por favor seleccione un contrato para continuar',
   'input_fondo_gtia': 'Fondo de garantia',
   'input_fondo_gtia_descripcion': 'Ingrese el fondo de garantia',
   'input_fecha_contabilizado': 'Fecha contabilizado',
   'input_pendiente_contabilizar': 'Pendiente de contabilizar',
   'input_pendiente_contabilizar_descripcion': 'Ingrese si es pendiente de contabilizar',
   'input_contabilizado': 'Contabilizado',
   'input_contabilizado_descripcion': 'Ingrese el concepto contabilizado',
   'input_linea_base': 'Linea base',
   'input_pu': 'Precio unitario',
   'input_descripcion_pu': 'Ingrese el precio unitario',
   'input_cantidad': 'Cantidad',
   'input_diasNotificarInicio':'Días a notificar antes de la fecha de inicio',
   'input_diasNotificarFin':'Días a notificar antes de la fecha de termino',
   'input_diasNotificarInicio_descripcion':'Ingrese los días a notificar antes de la fecha de inicio',
   'input_diasNotificarFin_descripcion':'Ingrese los días a notificar antes de la fecha de termino',
   'input_descripcion_cantidad': 'Ingrese la cantidad',
   'input_cantidad_ejecutada': 'Cantidad de ACT ejecutado(s)',
   'input_descripcion_cantidad_ejecutada': 'Ingrese la cantidad de: ACT ejecutado(s)',
   'input_comentarios': 'Comentarios',
   'input_comentarios_descripcion': 'Ingrese sus comentarios',
   'input_descripcion_unidad': 'Ingrese la unidad',
   'input_descripcion_concepto': 'Ingrese el ID concepto',
   'input_concepto': 'ID Concepto',
   'input_concepto_titulo': 'Título de la deductiva',
   'input_descripcion_concepto_titulo': 'Ingrese el título de la deductiva ',
   'input_validation_min_12': 'Debe de tener al menos 12 caracteres',
   'input_validation_min_4': 'Debe de tener al menos 4 caracteres',
   'input_validation_min_3': 'Debe de tener al menos 3 caracteres',
   'input_validation_min_2': 'Debe de tener al menos 2 caracteres',
   'input_validation_min_10_digitos': 'Debe de tener al menos 10 dígitos',
   'input_validation_max_15': 'Debe de tener máximo 15 caracteres',
   'input_validation_max_3': 'Debe de tener máximo 3 caracteres',
   'input_validation_max_150': 'Debe de tener máximo 150 caracteres',
   'input_validation_max_255': 'Debe de tener máximo 255 caracteres',
   'input_validation_max_25': 'Debe de tener máximo 25 caracteres',
   'input_validation_max_500': 'Debe de tener máximo 500 caracteres',
   'input_validation_max_50': 'Debe de tener máximo 50 caracteres',
   'input_validation_max_50_digitos': 'Debe de tener máximo 50 dígitos',
   'input_validation_max_13': 'Debe de tener máximo 13 caracteres',
   'input_validation_requerido': 'Requerido',
   'input_validation_formato_invalido': 'Formato invalido',
   'input_validation_min_10': 'Debe de tener al menos 10 caracteres',
   'input_validation_min_1': 'Debe de tener al menos 1 caracter',
   'input_validation_max_10': 'Debe de tener máximo 10 caracteres',
   'input_validation_max_10_digitos': 'Debe de tener al menos 10 dígitos',
   'input_validation_max_250': 'Debe de tener máximo 250 caracteres',
   'input_validation_GratherThanFin1': 'La fecha inicial no puede ser mayor a la fecha de término',
   'input_validation_GratherThanFin': 'La fecha límite no puede ser menor a la fecha de término',
   'input_validation_lessThanIni': 'La fecha final no puede ser menor a la fecha inicio',
   'input_validation_solo_numeros': 'Solo números son permitidos',
   'input_validation_password_coincidir': 'Las contraseñas deben de coincidir',
   'campo_avatar_component_tamano_maximo_imagenes': 'El tamaño máximo de imágenes permitidas para este proceso es de 1 MB, el tamaño de esta imagen es de',
   'tabla_dinamica_acciones_asignar_usuario': 'Asignar usuarios',
   'tabla_dinamica_acciones_parametros_contrato': 'Parametros del contrato',
   'drag_and_drop_component_titulo_1': 'Arrastre y suelte algunos archivos aquí, o haga clic para seleccionar archivos',
   'drag_and_drop_component_titulo_2': 'Arrastre y suelte el archivo aquí, o haga clic para seleccionar el archivo',
   'login_form_component_acceder': 'Aceptar',
   'menu_confirmar_avance': 'Confirmar avance',
   'menu_carga_conceptos': 'Agregar concepto',
   'menu_empleados': 'Empleados',
   'menu_material': 'Material UI',
   'menu_dashboard': 'Panel',
   'menu_agrega_grafica': 'Agrega grafica',
   'menu_carga_imagenes': 'Carga medios',
   'menu_vista_previa_imagenes': 'Vista previa imágenes',
   'menu_catalogos': 'Catálogos',
   'menu_permisos-usuario': 'Permisos usuario',
   'menu_repositorio': 'Repositorio',
   'menu_regresar_inicio': 'Ir al inicio',
   'menu_cerrar_sesion': 'Cerrar sesión',
   'menu_cerrar_sesion_salir_sistema': 'Salir del sistema',
   'menu_iniciar_sesion': 'Iniciar sesión',

   'menu_ver_estimacion': 'Ver estimación',
   'menu_agregar_docs': 'Agregar documentos',
   'menu_ver_bitacora': 'Ver bitácora',
   'menu_generar_pdf': 'Generar PDF',
   'menu_editar_estatus': 'Editar estatus',
   'menu_editar_estimacion': 'Editar estimación',
   'menu_home_titulo': 'Módulos',
   'input_fecha_pago':'Fecha pago',
   'lang_mx': 'Español',
   'lang_eu': 'English',
   'page_titulo_lista_estimaciones': 'Lista de estimaciones definitivas',
   'page_titulo_carga_documentos_estimacion': 'Cargar documentos a estimación',

   'sesion_trabajo_contratos_titulo': 'Contratos vigentes',

   'ver_estimacion_tab_1_conceptos_estimados': "Conceptos estimados",
   'ver_estimacion_tab_2_documentos_cargados_estimacion': "Documentos cargados estimación",
   'ver_estimacion_tab_3_documentos_calidad': "Documentos de calidad",
   'ver_estimacion_tab_4_deductivas': "Deductivas",
   'ver_estimacion_tab_5_deductivas_adicionales': "Deductivas adicionales",

   'muestra-tolerancia-superada-1': 'El importe del catálogo cargado es de',
   'muestra-tolerancia-superada-2': 'La diferencia entre lo capturado y el catálogo es de',
   'muestra-tolerancia-superada-3': 'La tolerancia capturada para el contrato es de',
   'muestra-tolerancia-superada-4': 'El catálogo cargado está por encima del importe capturado',
   'muestra-tolerancia-superada-5': '¿Estas seguro que quieres cargar el catálogo?',
   'muestra-tolerancia-superada-aceptar': 'Conservar catálogo',
   'muestra-tolerancia-superada-cancelar': 'Eliminar catálogo',
   'input_mensaje': 'Mensaje',
   'input_mensaje_descripcion': 'Escriba su mensaje',
   'input_telefono_contacto': 'Teléfono',
   'input_telefono_contacto_descripcion': 'Ingrese el teléfono de contacto',
   'input_correo_contacto': 'Correo eléctronico',
   'input_correo_contacto_descripcion': 'Ingrese el correo eléctronico de contacto',
   'http_exito_contacto':'¡Gracias por su mensaje!, de inmediato nos pondemos en contacto con usted',
   'input_direccion':'Dirección',
   'input_direccion_descripcion':'Ingrese la dirección',
   'http_error_contacto':'Algo salio mal, por favor intente de nuevo',
   'btn_programar_hitos':'Programar hitos',
   'btn_agregar_hitos':'Agregar hitos',
   'btn_ver_programa_completo':'Ver programa completo',
   'btn_solicitar_autorizacion_programa':'Solicitar autorización programa',
   'input_porcentaje':'Porcentaje participación',
   'btn_agregar_responsables':'Agregar responsables',
   'menu_enviar_revision':'Enviar a revisión',
   'menu_revisar':'Revisar',
   'menu_enviar_coordinacion':'Enviar a auditar',
   'general_ver_documentos':"Ver documentos",
   'input_num_convenio':'Número de convenio',
   'input_num_convenio_descripcion':'Ingrese el número de convenio',
   'menu_generar_paquete':'Generar paquete',
   'general_agregar_foto_video':'Agregar foto/video',
   'general_agregar_nota':'Agregar nota',
   'general_agregar_avance':'Agregar avance',
   'general_agregar_documento':'Agregar documento',
   'general_aprobar_concepto':'Aprobar concepto',
   'general_deshabilitar_concepto':'Deshabilitar concepto',
   'general_habilitar_concepto':'Habilitar concepto',
   'general_revisar_documentos':'Validar documentos',
   'general_mostrar':'Mostrar',
   'add_documento_calidad':'Agregar',
   'add_documento_calidad_comentario':'Agregar comentario',
   'http_exito_al_enviar_documentos':'Exito al enviar la documentación',
   'http_error_al_enviar_documentos':'Error al enviar la documentación',
   'input_prioridad':'Prioridad',
   'input_codigo':'Código',
   'input_concepto_':'Concepto',
   'input_incidencia':'Incidencia',
   'input_cantidad_descripcion':'Ingrese la cantidad',
   'input_codigo_descripcion':'Ingrese el código',
   'input_concepto__descripcion':'Ingrese el concepto ',
   'input_incidencia_descripcion':'Ingrese la incidencia',
   'input_punto_reorden':'Punto de reorden',
   'input_punto_reorden_descripcion':'Ingrese el punto de reorden',
   'general_registrar_salida':'Registrar salida',
   'general_registrar_entrada':'Registrar entrada',
   'general_ver_kardex':'Ver kardex',
   'reportes_inteligentes_titulo_crear_reporte_imagen':'Crear reporte de imagen',
   'reportes_inteligentes_titulo_crear_reporte_voz':'Crear reporte de voz',
   'reportes_inteligentes_titulo_reportes_creados':'Reportes creados',
   'reportes_inteligentes_titulo_generar_resumen_global':'Generar resúmen global',
   'reportes_inteligentes_titulo_consulta_resumen_global':'Consulta de resúmenes globales',
   'reportes_inteligentes_titulo_parametros_analisis_imagen':'Parametros de análisis en imagenes',
   'input_parametro':'Parametros de análisis',
   'input_tipoReporte':'Tipo de reporte',
   'input_palabras_clave':'Palabas clave',
   'input_palabras_clave_descripcion':'Ingrese la palabra y presione enter para agregar la palabra a los parámetros de búsqueda.',
   'plan_maestro_title_1':'Por contratista',
   'plan_maestro_title_2':'Por clasificación',
   'general_guardar_carpeta_compartida':'Crear carpeta compartida',
   'menu_carga_AI':'Reportes IA',
   'input_consulta_estimaciones_por':'Consulta de estimaciones por',
   'input_estatus_estimacion':'Estatus de estimación',
   'general_ver_estimacion':'Ver estimación',
   'general_ver_bitacora':'Ver bitacora',
   'general_procesando_306':'Procesando en 360',
   'general_ver_detalle':'Ir al detalle',
   'input_ano_seleccion':'Fecha',
   'input_clasificacion':'Clasificación',
   'input_clasificacion_descripcion':'Ingrese la descripción de la clasificación',
   'input_pregunta_asistente':'Pregunta',
   'input_pregunta_asistente_descripcion':'Preguntale algo al asistente, prueba con algo como "En que puedes asistirme"',
   'general_agregar_valores_proyecto' : 'Agregar valores',

   'input_catValor': 'Tipo de valor',
   'general_pedido': 'Pedido',
   'input_pedido_descripcion': 'Ingrese el pedido',
   'general_ver_valores_proyecto':'Ver valores',
   'general_agregar_valores_conceptos':'Agregar conceptos',
   'general_ver_valores_catalogo':'Ver valores catálogo',
   'input_carpeta':'Carpeta',
   'input_presupuesto_param':'Presupuesto parametrizado',
   'input_cotizado':'Cotizado',
   'input_presupuesto_param_descripcion':'Ingrese el presupuesto parametrizado',
   'input_cotizado_descripcion':'Ingrese el valor cotizado',
   'input_peps_multiples':'Tu contrato cuenta con multiples cuentas contables, agregalas aquí',
   'input_motivo':'Motivo',
   'input_motivo_descripcion':'Ingrese el motivo',
   'input_convenio':'Convenio',
   'input_convenio_descripcion':'Ingrese el convenio',
   'input_programa':'Programa',
   'general_aplicar_programa':'Aplicar programa',
   'general_ver_programa':'Ver programa',
   'http_exito_aplicar_programa':'Exito al aplicar el programa financiero',
   'http_error_aplicar_programa':'Error al aplicar el programa financiero',
   'general_aceptar':'Aceptar',
   'stepper_geocercas_usuarios_paso_0': 'Tipo de usuario',
   'stepper_geocercas_usuarios_paso_1': 'Formulario usuario nuevo',
   'stepper_geocercas_usuarios_paso_2': 'formulario seleccion de usuario existente',
   'alta_usuarios_geocerca_confirmacion': '¡Ha finalizado el registro del usuarios!',
   'input_contratos':'Contratos',
   'input_usuarios':'Usuarios',
   'general_temporal':'Guardar información temporalmente',
   'input_tarea_id':'Eventos que desea notificar',
   'input_reenviar':'Intervalo de ejecución',
   'input_horario' : 'Horario',
   'input_correo': 'Correo electrónico',
   'input_telefono_whats': 'Teléfono celular (WhatsApp)',
   'input_descripcion_telefono_whats':'Ingrese el número de celuar',
   'input_notificacion_en_sistema':'Notificar en el sistema APM',
   'input_descripcion_correo': 'Ingrese el correo electrónico',
   'input_texto_banner':'Texto banner',
   'input_texto_banner_descripcion':'Ingrese el texto que va a ir en el elemento del banner',
   'input_piso':'Piso',
   'input_play_list':'Lista de reproducción',
   'input_play_list_descripcion':'Elija las listas de reproducción a las que desea incluir el elmento',
   'input_dispositivo':'Dispositivo'
};

export default textosMx;

